DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(168) NOT NULL,
    surname VARCHAR(168) NOT NULL,
    email VARCHAR(168) NOT NULL UNIQUE,
    password VARCHAR(168) NOT NULL,
    imageUrl TEXT

);
